title: Data Analytics Course
description: A full data analytics learning path, hosted with GitHub Pages.
theme: jekyll-theme-minimal

# Optional: (but good to have)
markdown: kramdown
kramdown:
  input: GFM

# Keep the folders clean
permalink: pretty


# Optional: Allow future extension with collections
collections:
  lessons:
    output: true
    permalink: /:path/
